os: linux

# we use the R VM because it contains LaTeX and pandoc
language: r

# we need super user privileges, so we depend on the old travis-ci infrastructure
sudo: required

# we can install additional software
apt_packages:
# we download pdf2djvu to also generate a djvu file of our LaTeX source
  - pdf2djvu

script:
# if you have a markdown source, you can use pandoc to convert it to a LaTeX document
  - pandoc -s --from=markdown_github --to=latex -V geometry:letter,margin=1in -o README.tex README.md

# in the next step we use pdflatex to convert .tex to .pdf
# of course we could use pandoc for this also, but pdflatex generates nicer PDFs
  - pdflatex -interaction=nonstopmode master.tex
  - pdflatex -interaction=nonstopmode README.tex
  - pdflatex -interaction=nonstopmode lab01/lab01.tex
  - pdflatex -interaction=nonstopmode lab01/notes01.tex
  - pdflatex -interaction=nonstopmode lab02/lab02.tex
  - pdflatex -interaction=nonstopmode lab02/notes02.tex
  - pdflatex -interaction=nonstopmode lab03/lab03.tex
  - pdflatex -interaction=nonstopmode lab03/notes03.tex
  - pdflatex -interaction=nonstopmode lab04/lab04.tex
  - pdflatex -interaction=nonstopmode lab04/notes04.tex
  - pdflatex -interaction=nonstopmode lab05/lab05.tex
  - pdflatex -interaction=nonstopmode lab05/notes05.tex
  - pdflatex -interaction=nonstopmode lab06/lab06.tex
  - pdflatex -interaction=nonstopmode lab06/notes06.tex
  - pdflatex -interaction=nonstopmode lab07/lab07.tex
  - pdflatex -interaction=nonstopmode lab07/notes07.tex
  - pdflatex -interaction=nonstopmode lab08/lab08.tex
  - pdflatex -interaction=nonstopmode lab08/notes08.tex
  - pdflatex -interaction=nonstopmode lab09/lab09.tex
  - pdflatex -interaction=nonstopmode lab09/notes09.tex
  - pdflatex -interaction=nonstopmode lab10/lab10.tex
  - pdflatex -interaction=nonstopmode lab10/notes10.tex
  - pdflatex -interaction=nonstopmode lab11/lab11.tex
  - pdflatex -interaction=nonstopmode lab11/notes11.tex
  - pdflatex -interaction=nonstopmode lab12/lab12.tex
  - pdflatex -interaction=nonstopmode lab12/notes12.tex

# now we convert the pdf file to a much smaller djvu document  
  - pdf2djvu -d 1200 -o master.djvu master.pdf
after_success:
# upload the previously generated pdf file to simonwaldherr.de (use $UPLOADSECRET as password)

deploy:

# provider releases means GitHub Releases
  provider: releases
  api_key:

# Travis CI public key encrypted GitHub oauth key for pushing to GitHub Releases
    secure: UNfN17F/m8PSbbU53/xHGqySzA/pyyrWIc42o6Mnb3EzOMlAhTLsHvnOTw8L27KEeszyZJp8TcyG0PCnFfTgzV3gWMc1tweLnPBwWYj+qFWqQyqc8pkG4xfMrEAfbFk20sYGQYoRnaws85uc/nCcXNhVKvcFMCaZUYcxJKV/Kdass4rsfc205nRqvXa3unWlg51YzNtAB2glGbhe9/Rw6SeeTJiUmcjWKPDEhTfCTF8X0d4QaM6RiDly+Vfzv9POf+FRk8HWrmiImxguxepHhb5Ellz7hPZlTQ6iEb+igzde7jxxUKc4otFSrDG45TLoQ8BKsf32AMUo/JjXMT29H2alEF3P/6pSaev2M9gyVsQbzCfxUQOUn5HilY0D3khEIiT1smK0LrQPrQcarldN4BLJm/WG9pzsjKOp3PZQ6Afy1TOG2LPJv+xOIJFhYHNQSp+jjRaPLxbDwcZfxGFPPTDJ2xJvPEoNjL3vT1bdppGgopZxShqmxxzolBMoG0Y+H87DKu7Zv8u3yyjxneP1dhb+StsTLS7GzahD3J2WjHos9UYZV2BGitMyy2j7GJQ5+oPBH3HdoiLjU8BcTOOQ7ZX6xDxBaA9MyT+Q6pYFuxpZkbmB/7GZFnizP7Hpf5WExGVIqlIeYM6zZSaha49SPWxdQSHDLZTUHVGcG4tDbLY=

# the list of files to upload
  file: 
    - "master.pdf"
    - "README.pdf"
    - "master.djvu"
  skip_cleanup: true
  on:
    repo: wdconinc/electronics