os: linux
sudo: required
language: ruby

before_install:
 - sudo apt-add-repository -y ppa:texlive-backports/ppa
 - sudo apt-get update -q
 - sudo apt-get install -y pandoc rubber texlive-science texlive-pictures texlive-latex-extra

script:
 - sed -i 's|^\[\!\[.*||g' README.md
 - pandoc -s --from=markdown --to=latex -V geometry:letterpaper,margin=1in -o README.tex README.md
 - rubber --pdf README.tex

 - pandoc -s --from=markdown --to=latex -V geometry:letterpaper,margin=1in -o LICENSE.tex LICENSE.md
 - rubber --pdf LICENSE.tex

 - rubber --pdf lab01/lab01.tex
 - rubber --pdf lab01/notes01.tex
 - rubber --pdf lab02/lab02.tex
 - rubber --pdf lab02/notes02.tex
 - rubber --pdf lab03/lab03.tex
 - rubber --pdf lab03/notes03.tex
 - rubber --pdf lab04/lab04.tex
 - rubber --pdf lab04/notes04.tex
 - rubber --pdf lab05/lab05.tex
 - rubber --pdf lab05/notes05.tex
 - rubber --pdf lab06/lab06.tex
 - rubber --pdf lab06/notes06.tex
 - rubber --pdf lab07/lab07.tex
 - rubber --pdf lab07/notes07.tex
 - rubber --pdf lab08/lab08.tex
 - rubber --pdf lab08/notes08.tex
 - rubber --pdf lab09/lab09.tex
 - rubber --pdf lab09/notes09.tex
 - rubber --pdf lab10/lab10.tex
 - rubber --pdf lab10/notes10.tex
 - rubber --pdf lab11/lab11.tex
 - rubber --pdf lab11/notes11.tex
 - rubber --pdf lab12/lab12.tex
 - rubber --pdf lab12/notes12.tex

deploy:
  provider: releases
  api_key:
    secure: FR+gX4RrmfM013JER9FwsxzBxzC0wk2XU0ZWlJQDh2cT01gIImmyMTK61WD+EpzOoXaar+YV1Qb99ZHw/83mRtBMfdxPXhHvaYR9z/MWnkTaYsQNGPhaukp2tPSMwURJYCpt+T+aTBbg1u9LrZaZZPpXCJQ8DxYWnpZGjEhNiP3YAxxvFnIN1cVCAU7GHyfPVOjrKaRp7cGmwzBZ0HcLKSTozRvZjeohQp5rkNPUuw8B4docIeESq8GFlmhIGx4SUfRWnA7pma3AQBH9imkktdPfqlt0dQ/8p+XEA1D+IDjLM+oZGfFIQ/lneMX1CDcvROQXeUXNTblPjYrJzEJFWykHR64bxlpmGjDsG6XfgBFd7Y9SoOW1crcoAfpDnmNBDpPQ1RpCIf9b9YaUxn8/WVIiamIisLHYJoCqQ0Lv9q4HEyNUZe3WEZExeNPddVqYzBdEmysa5pqPQhADbUrPilFbcVxQrI9YHRk/WBItUWCAjs8vE5XaCKHsLjDrvHGEDAoHb5QSbkRm5smhDRU6MVjwHLTX4ugEcuMGFAh7/qpj+KoBTaxx+K9VW4noXds/hHQf3cJ8Y9PZnZer6Sb6LCWmQJVEdCPVdiJKwdpPrU40R+NgGMCBcZ0eiirBWcrVl6bwjrG4QchqHO8Rkvx0i5RNBuy248taTMatGFhqJGE=
  file:
   - README.pdf
   - LICENSE.pdf
  on:
    repo: wdconinc/electronics
