os: linux
dist: trusty
sudo: required
language: ruby

before_install:
- sudo apt-get install -y pandoc rubber
- sudo apt-get install -y texlive-fonts-recommended texlive-fonts-extra
- sudo apt-get install -y texlive-latex-recommended texlive-latex-extra
- sudo apt-get install -y texlive-science texlive-pictures
- sudo apt-get install -y texlive-xetex

script:
- sed -i 's|^\[\!\[.*||g' README.md
- pandoc -s --from=markdown --to=latex -V geometry:letterpaper,margin=1in -o README.tex README.md
- rubber --pdf README.tex

- pandoc -s --from=markdown --to=latex -V geometry:letterpaper,margin=1in -o LICENSE.tex LICENSE.md
- rubber --pdf LICENSE.tex

- rubber --pdf lab01/lab01.tex
- rubber --pdf lab01/notes01.tex
- rubber --pdf lecture01/lecture01_handouts.tex
- rubber --pdf lecture01/lecture01_presentation.tex

- rubber --pdf lab02/lab02.tex
- rubber --pdf lab02/notes02.tex
- rubber --pdf lecture02/lecture02_handouts.tex
- rubber --pdf lecture02/lecture02_presentation.tex

- rubber --pdf lab03/lab03.tex
- rubber --pdf lab03/notes03.tex
- rubber --pdf lecture03/lecture03_handouts.tex
- rubber --pdf lecture03/lecture03_presentation.tex

- rubber --pdf lab04/lab04.tex
- rubber --pdf lab04/notes04.tex
- rubber --pdf lecture04/lecture04_handouts.tex
- rubber --pdf lecture04/lecture04_presentation.tex

- rubber --pdf lab05/lab05.tex
- rubber --pdf lab05/notes05.tex
- rubber --pdf lecture05/lecture05_handouts.tex
- rubber --pdf lecture05/lecture05_presentation.tex

- rubber --pdf lab06/lab06.tex
- rubber --pdf lab06/notes06.tex
- rubber --pdf lecture06/lecture06_handouts.tex
- rubber --pdf lecture06/lecture06_presentation.tex

- rubber --pdf lab07/lab07.tex
- rubber --pdf lab07/notes07.tex
- rubber --pdf lecture07/lecture07_handouts.tex
- rubber --pdf lecture07/lecture07_presentation.tex

- rubber --pdf lab08/lab08.tex
- rubber --pdf lab08/notes08.tex
- rubber --pdf lecture08/lecture08_handouts.tex
- rubber --pdf lecture08/lecture08_presentation.tex

- rubber --pdf lab09/lab09.tex
- rubber --pdf lab09/notes09.tex
- rubber --pdf lecture09/lecture09_handouts.tex
- rubber --pdf lecture09/lecture09_presentation.tex

- rubber --pdf lab10/lab10.tex
- rubber --pdf lab10/notes10.tex
- rubber --pdf lecture10/lecture10_handouts.tex
- rubber --pdf lecture10/lecture10_presentation.tex

- rubber --pdf lab11/lab11.tex
- rubber --pdf lab11/notes11.tex
- rubber --pdf lecture11/lecture11_handouts.tex
- rubber --pdf lecture11/lecture11_presentation.tex

- rubber --pdf lab12/lab12.tex
- rubber --pdf lab12/notes12.tex
- rubber --pdf lecture12/lecture12_handouts.tex
- rubber --pdf lecture12/lecture12_presentation.tex

- rubber --pdf electronics_labs.tex
- rubber --pdf electronics_handouts.tex

deploy:
  provider: releases
  api_key:
    secure: c42Ygc5l72reee2weXOpiFoNsOlJ6RJ46wdF9D++QqBzMLRrHL8luBET/GbGXRwhPohUFLun7RTsGlcyGLkqWNP/Aj7iVRoA/69LYNNKPrRAWAFAxiGN0OdY/w6YEj4wZ+UHe3DkOJ0WL69P9oS69glDT0pMdmNWLTC62DKPOt5NpAThgAhXv8MpeNWawq1Qv1eK/c2C4d7TJvlU7K4OqEY3wl5mXyakj2/hmuLG1vUJqxLAGgwI1KcvGQDjAe+tOeGPcSVTfYUD0RpCUDYbJWdEv1CzEmHj6OJrvsL3GVr/5Ti4AuZh/n9QkNztVg14DCuEIMmIdxoRElTF4Hv9gb3AK12KB4+aWMyXxsnqiUBmXSFSe2R9bHERJw942rekxrk4CZd9sghdSi30GjPJrzpzNPSePL7drQmrrDC8g4F5BiLfXVRcxu5ZWySnU+F6CNicyp35RitW1K/xQMOkZ3iIvS3Ko1it9CES5kZb7L50W0+8VObgqEOafREcMuE4Qzra6XDVwidKQXoR5aBscvDYiTatpKS1F3xsKfgzxNCyrFfDsjIEYhqUXYU12+4Vo8cymR2WA/8MtpwRPNMACijoSOWTGE4nOuu+rIkuHZHlS0B/Abyu7KNx1f/l1dU4qBYwrPN4vDbGHJtmmHcB0U3tiaclGyc2YrMnVfrAzc8=
  file:
  - README.pdf
  - LICENSE.pdf
  - electronics_labs.pdf
  - electronics_handouts.pdf
  - lab01.pdf
  - lab02.pdf
  - lab03.pdf
  - lab04.pdf
  - lab05.pdf
  - lab06.pdf
  - lab07.pdf
  - lab08.pdf
  - lab09.pdf
  - lab10.pdf
  - lab11.pdf
  - lab12.pdf
  - notes01.pdf
  - notes02.pdf
  - notes03.pdf
  - notes04.pdf
  - notes05.pdf
  - notes06.pdf
  - notes07.pdf
  - notes08.pdf
  - notes09.pdf
  - notes10.pdf
  - notes11.pdf
  - notes12.pdf
  - lecture01_handouts.pdf
  - lecture02_handouts.pdf
  - lecture03_handouts.pdf
  - lecture04_handouts.pdf
  - lecture05_handouts.pdf
  - lecture06_handouts.pdf
  - lecture07_handouts.pdf
  - lecture08_handouts.pdf
  - lecture09_handouts.pdf
  - lecture10_handouts.pdf
  - lecture11_handouts.pdf
  - lecture12_handouts.pdf
  - lecture01_presentation.pdf
  - lecture02_presentation.pdf
  - lecture03_presentation.pdf
  - lecture04_presentation.pdf
  - lecture05_presentation.pdf
  - lecture06_presentation.pdf
  - lecture07_presentation.pdf
  - lecture08_presentation.pdf
  - lecture09_presentation.pdf
  - lecture10_presentation.pdf
  - lecture11_presentation.pdf
  - lecture12_presentation.pdf
  skip_cleanup: true
  on:
    repo: wdconinc/electronics
