os: linux
dist: trusty
sudo: required
language: ruby

before_install:
- sudo apt-get install -y pandoc rubber
- sudo apt-get install -y texlive-fonts-recommended texlive-fonts-extra
- sudo apt-get install -y texlive-latex-recommended texlive-latex-extra
- sudo apt-get install -y texlive-science texlive-pictures
- sudo apt-get install -y texlive-xetex

script:
- sed -i 's|^\[\!\[.*||g' README.md
- pandoc -s --from=markdown --to=latex -V geometry:letterpaper,margin=1in -o README.tex README.md
- rubber --pdf README.tex

- pandoc -s --from=markdown --to=latex -V geometry:letterpaper,margin=1in -o LICENSE.tex LICENSE.md
- rubber --pdf LICENSE.tex

- for i in `seq -w 01 12` ; do 
    rubber --pdf lab${i}/lab${i}.tex
    rubber --pdf lab${i}/notes${i}.tex
    rubber --pdf lecture${i}/lecture${i}_handouts.tex
    rubber --pdf lecture${i}/lecture${i}_presentation.tex
  done

- rubber --pdf electronics_labs.tex
- rubber --pdf electronics_handouts.tex

deploy:
  provider: releases
  api_key:
    secure: c42Ygc5l72reee2weXOpiFoNsOlJ6RJ46wdF9D++QqBzMLRrHL8luBET/GbGXRwhPohUFLun7RTsGlcyGLkqWNP/Aj7iVRoA/69LYNNKPrRAWAFAxiGN0OdY/w6YEj4wZ+UHe3DkOJ0WL69P9oS69glDT0pMdmNWLTC62DKPOt5NpAThgAhXv8MpeNWawq1Qv1eK/c2C4d7TJvlU7K4OqEY3wl5mXyakj2/hmuLG1vUJqxLAGgwI1KcvGQDjAe+tOeGPcSVTfYUD0RpCUDYbJWdEv1CzEmHj6OJrvsL3GVr/5Ti4AuZh/n9QkNztVg14DCuEIMmIdxoRElTF4Hv9gb3AK12KB4+aWMyXxsnqiUBmXSFSe2R9bHERJw942rekxrk4CZd9sghdSi30GjPJrzpzNPSePL7drQmrrDC8g4F5BiLfXVRcxu5ZWySnU+F6CNicyp35RitW1K/xQMOkZ3iIvS3Ko1it9CES5kZb7L50W0+8VObgqEOafREcMuE4Qzra6XDVwidKQXoR5aBscvDYiTatpKS1F3xsKfgzxNCyrFfDsjIEYhqUXYU12+4Vo8cymR2WA/8MtpwRPNMACijoSOWTGE4nOuu+rIkuHZHlS0B/Abyu7KNx1f/l1dU4qBYwrPN4vDbGHJtmmHcB0U3tiaclGyc2YrMnVfrAzc8=
  file:
  - README.pdf
  - LICENSE.pdf
  - electronics_labs.pdf
  - electronics_handouts.pdf
  - lab01.pdf
  - lab02.pdf
  - lab03.pdf
  - lab04.pdf
  - lab05.pdf
  - lab06.pdf
  - lab07.pdf
  - lab08.pdf
  - lab09.pdf
  - lab10.pdf
  - lab11.pdf
  - lab12.pdf
  - notes01.pdf
  - notes02.pdf
  - notes03.pdf
  - notes04.pdf
  - notes05.pdf
  - notes06.pdf
  - notes07.pdf
  - notes08.pdf
  - notes09.pdf
  - notes10.pdf
  - notes11.pdf
  - notes12.pdf
  - lecture01_handouts.pdf
  - lecture02_handouts.pdf
  - lecture03_handouts.pdf
  - lecture04_handouts.pdf
  - lecture05_handouts.pdf
  - lecture06_handouts.pdf
  - lecture07_handouts.pdf
  - lecture08_handouts.pdf
  - lecture09_handouts.pdf
  - lecture10_handouts.pdf
  - lecture11_handouts.pdf
  - lecture12_handouts.pdf
  - lecture01_presentation.pdf
  - lecture02_presentation.pdf
  - lecture03_presentation.pdf
  - lecture04_presentation.pdf
  - lecture05_presentation.pdf
  - lecture06_presentation.pdf
  - lecture07_presentation.pdf
  - lecture08_presentation.pdf
  - lecture09_presentation.pdf
  - lecture10_presentation.pdf
  - lecture11_presentation.pdf
  - lecture12_presentation.pdf
  skip_cleanup: true
  on:
    repo: wdconinc/electronics
